In [14]:
#from google.colab import drive
#drive.mount('/content/drive')
#%cd /content/drive/MyDrive/Prj

In [15]:
!python3 -V

Python 3.7.12


In [16]:
#!git clone https://github.com/HamaruKi0303/Basketball-Action-Recognition

In [17]:
#%cd Basketball-Action-Recognition

In [18]:
#!pip install -r requirements.txt

In [19]:
!pip install vidaug

In [20]:
#!wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1hLpbLmLFK2-GIvsmpJelGlEx94yQM2Ts' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1hLpbLmLFK2-GIvsmpJelGlEx94yQM2Ts" -O datasets.zip && rm -rf /tmp/cookies.txt

In [21]:
#!unzip datasets.zip

In [22]:
!mkdir model_checkpoints
#!wget https://download.pytorch.org/models/r2plus1d_18-91a641e6.pth -P model_checkpoints

mkdir: cannot create directory ‘model_checkpoints’: File exists
--2023-02-03 13:17:05--  https://download.pytorch.org/models/r2plus1d_18-91a641e6.pth
Resolving download.pytorch.org (download.pytorch.org)... 13.249.146.93, 13.249.146.39, 13.249.146.45, ...
Connecting to download.pytorch.org (download.pytorch.org)|13.249.146.93|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 126162996 (120M) [binary/octet-stream]
Saving to: ‘model_checkpoints/r2plus1d_18-91a641e6.pth.1’

r2plus1d_18-91a641e 100%[===================>] 120.32M  9.38MB/s    in 13s     

2023-02-03 13:17:18 (9.14 MB/s) - ‘model_checkpoints/r2plus1d_18-91a641e6.pth.1’ saved [126162996/126162996]



In [23]:
!mkdir -p dataset/augmented-examples/

In [24]:
#!cp model_checkpoints/r2plus1d_18-91a641e6.pth model_checkpoints/r2plus1d_multiclass_19_0.0001.pt

In [25]:
import json
from collections import OrderedDict
import pprint

In [26]:
labels_dict = \
{
    0 : "block",
    1 : "pass",
    2 : "run",
    3 : "dribble",
    4 : "shoot",
    5 : "ball in hand",
    6 : "defense",
    7 : "pick",
    8 : "no_action",
    9 : "walk",
    10 : "discard"
}

In [27]:
labels_dict

{0: 'block',
 1: 'pass',
 2: 'run',
 3: 'dribble',
 4: 'shoot',
 5: 'ball in hand',
 6: 'defense',
 7: 'pick',
 8: 'no_action',
 9: 'walk',
 10: 'discard'}

In [28]:
with open('dataset/labels_dict.json', 'w') as f:
    json.dump(labels_dict, f, indent=4)

In [29]:
!python3 augment_videos.py

Percentage 1.0 : 100%|███████████████████| 37085/37085 [02:16<00:00, 271.08it/s]


In [30]:
!ls /content/Basketball-Action-Recognition/dataset/examples

ls: cannot access '/content/Basketball-Action-Recognition/dataset/examples': No such file or directory


In [ ]:
!python3 train.py

PyTorch Version:  1.11.0
Torchvision Version:  0.12.0
/opt/conda/lib/python3.7/site-packages/torch/cuda/__init__.py:145: UserWarning: 
NVIDIA GeForce RTX 3060 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_60 sm_70 sm_75 compute_70 compute_75.
If you want to use the NVIDIA GeForce RTX 3060 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Current Device:  0
Device:  <torch.cuda.device object at 0x7f00c7a50310>
Cuda Is Available:  True
Device Count:  1
Downloading: "https://download.pytorch.org/models/r2plus1d_18-91a641e6.pth" to /root/.cache/torch/hub/checkpoints/r2plus1d_18-91a641e6.pth
100%|████████████████████████████████████████| 120M/120M [00:12<00:00, 10.2MB/s]
VideoResNet(
  (stem): R2Plus1dStem(
    (0): Conv3d(3, 45, kernel_size=

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



Phase: train || Epoch: 8 || Loss 0.56900 :  86%|▊| 3765/4367 [34:00<05:25,  1.85

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



Phase: val || Epoch: 8 || Loss 4.43835 : 100%|█| 1248/1248 [09:14<00:00,  2.25it
val  training complete in 397m 31s
val Loss: 0.5550 Acc: 0.8485
[2 7 8 ... 1 9 2]
[2 7 8 ... 1 9 9]
Epoch: 8 || Val_Acc: 0.848496993987976 || Val_Loss: 0.555015689389475
val: 
[[ 939   11    0    0    5    1    7    2    1    7]
 [   5 1006    5   19    0    6    1    1    1    6]
 [   9    4  982   22    1    4   28    0    5  129]
 [   0   11   11  675    0    8    8    1    1    3]
 [   3    5    0    0  410    2    0    0    0    0]
 [   6   19   13   53    3  339   20    3   10   16]
 [   4    2   13    8    0    0  638    2   36   61]
 [   5   25    4    0    0    0    7  644    9    8]
 [   4    3    1    2    0    3  128    7  967  199]
 [   9    6   87    7    0    7  186   12  191 1868]]
Phase: train || Epoch: 9 || Loss 0.33703 :  19%|▏| 844/4367 [07:36<31:51,  1.84i

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



Phase: train || Epoch: 12 || Loss 0.36562 :  78%|▊| 3403/4367 [30:46<08:46,  1.8

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



Phase: train || Epoch: 15 || Loss 0.29583 : 100%|█| 4367/4367 [39:36<00:00,  1.8
train  training complete in 729m 24s
train Loss: 0.0370 Acc: 0.9879
[1 0 4 ... 9 6 9]
[1 0 4 ... 9 6 9]
Epoch: 15 || Train_Acc: 0.9878904125275543 || Train_Loss: 0.036983523903443026
train: 
[[3471    9    1    1    3    1    3    2    2    4]
 [   6 3712    2    3    2    4    0    6    2    6]
 [   4    1 4098   11    0    1    2    1    0   27]
 [   0    2    7 2417    0    9    7    0    1    4]
 [   5    1    0    1 1490    0    0    0    1    2]
 [   1    5    4    6    3 1642    4    0    5    2]
 [   5    0    5    6    0    3 2636    2   15   20]
 [   2    5    1    0    0    0    2 2483    6    2]
 [   1    2    1    1    0    2   17    3 4444   51]
 [   1    2   24    2    0    6   16    5   41 8115]]
Phase: val || Epoch: 15 || Loss 5.20871 : 100%|█| 1248/1248 [09:55<00:00,  2.09i
val  training complete in 739m 20s
val Loss: 0.6513 Acc: 0.8521
[2 7 8 ... 1 2 9]
[2 7 8 ... 1 9 9]
Epoch: 15 || Val

In [ ]:
!python3 inference.py

PyTorch Version:  1.11.0
Torchvision Version:  0.12.0
/opt/conda/lib/python3.7/site-packages/torch/cuda/__init__.py:145: UserWarning: 
NVIDIA GeForce RTX 3060 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_60 sm_70 sm_75 compute_70 compute_75.
If you want to use the NVIDIA GeForce RTX 3060 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Current Device:  0
Device:  <torch.cuda.device object at 0x7fa41025ca10>
Cuda Is Available:  True
Device Count:  1
VideoResNet(
  (stem): R2Plus1dStem(
    (0): Conv3d(3, 45, kernel_size=(1, 7, 7), stride=(1, 2, 2), padding=(0, 3, 3), bias=False)
    (1): BatchNorm3d(45, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): Conv3d(45, 64, kernel_size=(3, 1, 